trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: MLM_LICENSE_TOKEN

steps:
- task: InstallMATLAB@1
  inputs:
    products: 'MATLAB_Compiler'
- task: RunMATLABCommand@1
  inputs:
    command: 'compiler.build.standaloneApplication("hello.m");'
  env:
    MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
