version: 2.1
orbs:
  matlab: mathworks/matlab@1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - matlab/install:
          products: MATLAB_Compiler
      - matlab/run-command:
          command: 'compiler.build.standaloneApplication("hello.m");'

workflows:
  build:
    jobs:
      - build:
          context: MLM_LICENSE_TOKEN